<?php

namespace AppBundle\Repository;

/**
 * PostsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
