<?php

namespace AppBundle\Repository;

/**
 * ProjectsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
